export const ACTION_TYPES = {
  DARK_MODE: "DARK_MODE",
  TODO: {
    ADD_TODO: "ADD_TODO",
    DELETE_TODO: "DELETE_TODO",
    REMOVE_ALL_TODO: "REMOVE_ALL_TODO",
    EDIT_TODO: "EDIT_TODO",
  },
};
